### ISSUE TITLE
Upgrade to Bamboo specs 6.1.0

### ISSUE THREAD

**Issue by msessa** [thecodesmith/bamboo-specs-dsl#1]
Would it be possible to publish an new version compatible with Bamboo 6.1.0 specs?

**Comment by thecodesmith** [comment]
@msessa Thanks for opening the issue. Are there specific features from 6.1.0 you would like to see? I believe the current version is "compatible", but does not yet support any new features introduced in 6.1.0.

**Comment by msessa** [comment]
Hi @thecodesmith 
First of all, thanks for creating this project :) 

It's up to you if you want to maintain different branches for use with 6.0, 6.1 and in the future 6.2 etc 

I'd say for now just bump up the dependency version so that bamboo doesn't throw a compatibility error when applying the plan. New features can then be added via PRs, I'm happy to contribute as I get more familiar with the specs.

Thanks :)

**Comment by thecodesmith** [comment]
Done. Upgraded to Bamboo libraries to 6.2.1.
