### ISSUE TITLE
Remote builds?

### ISSUE THREAD

**Issue by MariusVolkhart** [thecodesmith/bamboo-specs-dsl#2]
Is it possible to have Bamboo build & execute the specs after checking them in? I'm trying to replicate the sort of system we see with Travis or CircleCI where my specs are in my project repository and the build plan is adjusted based on them.

I initially tried using Maven + Kotlin, but it seems that Bamboo replaces the plugin section of the POM & I can't seem to get it to work. I was curious, has anyone been able to use this project in such a manner?

**Comment by thecodesmith** [comment]
@MariusVolkhart That's a good question. When I originally implemented this DSL, such functionality was not available in Bamboo. However, it looks like Bamboo may have implemented this in the mean time: https://confluence.atlassian.com/bamboo/enabling-repository-stored-bamboo-specs-938641941.html. I have just updated the Bamboo Spec dependency to 6.5.0 and released version 0.10.3 of this library, which might be worth a try. I am not sure if that addresses your issue though.
